global:
  scrape_interval: 15s
  evaluation_interval: 15s
  scrape_timeout: 10s

  # Attach these labels to any time series or alerts when communicating with
  # external systems (federation, remote storage, Alertmanager).
  external_labels:
    monitor: "example"

# Alertmanager configuration
alerting:
  alertmanagers:
    - static_configs:
        - targets: ["localhost:9093"]

# Load rules once and periodically evaluate them according to the global 'evaluation_interval'.
rule_files:
  # - "first_rules.yml"
  # - "second_rules.yml"

scrape_configs:
  - job_name: "prometheus"
    scrape_interval: 1m
    scrape_timeout: 1m
    static_configs:
      - targets: ["localhost:9090"]

  # prometheus-node-exporter
  # - job_name: node
  #   static_configs:
  #     - targets: ['localhost:9100']

  - job_name: "main: Logger DB"
    scrape_interval: 1m
    static_configs:
      - targets: [localhost:5000]
  - job_name: "main: Logger update"
    scrape_interval: 1m
    static_configs:
      - targets: [localhost:5001]
  - job_name: "main: Controller DB"
    scrape_interval: 1m
    static_configs:
      - targets: [localhost:5002]
  - job_name: "main: Controller update"
    scrape_interval: 10m
    static_configs:
      - targets: [localhost:5003]
  - job_name: "main: Reporter"
    scrape_interval: 1h
    static_configs:
      - targets: [localhost:5005]
  # - job_name: "main: Flask Web App" # unused
  #   scrape_interval: 1s
  #   static_configs:
  #     - targets: [localhost:5004]

  - job_name: "debug"
    scrape_interval: 1s
    static_configs:
      - targets: [
            localhost:5100,
            localhost:5101,
            localhost:5102,
            localhost:5103,
            # localhost:5104, # unused: Flask Browser App
            localhost:5105,
          ]
